Repository crescenders/crescendo-frontend, pull requests merged in 2023-09, with the labels that each got.

#75 [CRES-74] feat: 상세페이지 API 연동
  next.config.js
  src/@types/index.d.ts
  src/apis/instance.ts
  src/apis/study/study.d.ts
  src/apis/study/studyApi.ts
  src/components/detail/StudyDetailContent.tsx
  src/hooks/queries/useGetStudy.ts
  src/mocks/data/studyList.json
  src/mocks/handlers/studyHandlers.ts
  src/pages/study/detail/[id].tsx
  src/pages/study/detail/assignment/[id].tsx
  src/utils/getDiffDate.ts
Labels: ✨ Feature

#77 [CRES-75] feat: 스터디 개설 API 연동
  src/apis/category/category.d.ts
  src/apis/category/categoryApi.ts
  src/apis/study/study.d.ts
  src/apis/study/studyApi.ts
  src/components/common/Slider.tsx
  src/hooks/mutations/useCreateStudy.ts
  src/hooks/queries/useGetCategories.ts
  src/hooks/queries/useGetProfile.ts
  src/hooks/useStudyForm.ts
  src/mocks/handlers/studyHandlers.ts
  src/pages/study/create/index.tsx
Labels: ✨ Feature

#79 [CRES-77] dangerouslySetInnerHTML로 파싱한 html이 스타일 리셋 설정으로 인해 원본 스타일이 나타나지 않는 문제 해결
  .yarn/cache/@tailwindcss-typography-npm-0.5.10-2b2ed3a63b-9e7cbef661.zip
  .yarn/cache/lodash.castarray-npm-4.4.0-f3706198e9-fca8c7047e.zip
  .yarn/cache/lodash.isplainobject-npm-4.0.6-d73937742f-29c6351f28.zip
  .yarn/cache/postcss-selector-parser-npm-6.0.10-a4d7aaa270-46afaa60e3.zip
  next.config.js
  package.json
  src/components/detail/StudyDetailContent.tsx
  tailwind.config.ts
  yarn.lock
Labels: fix

#81 [CRES-78] 카테고리 상수를 사용하는 기존 방식으로 변경
  src/pages/study/create/index.tsx
Labels: 🔙 Revert

#86 [CRES-79] refreshToken 저장 위치 쿠키로 변경
  src/apis/instance.ts
  src/components/common/NavigateList.tsx
  src/components/modal/LoginModal.tsx
  src/hooks/mutations/useDeleteUser.ts
  src/hooks/useUser.ts
  src/utils/cookie.ts
  src/utils/token.ts
Labels: 🛠️ Refactor

#90 [CRES-82] 상세페이지 컨텐츠 간격 조정, 가로 스크롤바 생기는 현상 수정
  src/components/common/Layout.tsx
  src/components/detail/StudyDetailContent.tsx
Labels: 🎨 design

#88 [CRES-71] middleware를 통해 로그인 여부에 따라 페이지 접근 제어 및 리다이렉션 적용
  src/components/common/Header.tsx
  src/hooks/queries/useGetProfile.ts
  src/middleware.ts
  src/pages/_app.tsx
Labels: ✨ Feature

#94 [CRES-83] 스터디 그룹 목록 검색 및 필터링 기능 구현
  src/@types/index.d.ts
  src/apis/study/study.d.ts
  src/apis/study/studyApi.ts
  src/components/common/Card.tsx
  src/components/common/Input.tsx
  src/components/common/SelectBox.tsx
  src/components/search/StudyList.tsx
  src/constants/search.ts
  src/hooks/queries/useGetStudy.ts
  src/hooks/useStudyList.ts
  src/mocks/handlers/studyHandlers.ts
  src/pages/index.tsx
  src/pages/search/index.tsx
Labels: ✨ Feature

#99 [CRES-84] 스터디 개설자의 본인 여부를 판단해 수정/삭제 버튼을 노출하고 마감된 스터디일시 수정을 금지한다.
  src/apis/study/study.d.ts
  src/components/common/Card.tsx
  src/components/common/Header.tsx
  src/components/detail/StudyDetailContent.tsx
  src/components/modal/LoginModal.tsx
  src/components/search/StudyList.tsx
  src/hooks/queries/useGetStudy.ts
  src/hooks/useUser.ts
  src/pages/index.tsx
  src/recoil/auth.ts
Labels: ✨ Feature

#101 [CRES-86] 스터디 상세페이지 스켈레톤 UI 구현
  src/components/skeleton/StudyDetailSkeleton.tsx
  src/pages/study/detail/[id].tsx
  tailwind.config.ts
Labels: ✨ Feature

#106 [CRES-92] useSuspenseQuery를 사용하기 위한 v5 마이그레이션
  .yarn/cache/@tanstack-match-sorter-utils-npm-8.8.4-488b98c113-d005f50075.zip
  .yarn/cache/@tanstack-query-core-npm-4.33.0-10e4a91d19-fae325f1d7.zip
  .yarn/cache/@tanstack-query-core-npm-5.0.0-rc.1-de3c05c11a-7c1a0409c5.zip
  .yarn/cache/@tanstack-query-devtools-npm-5.0.0-rc.1-8c47a9c0be-3abccc4c37.zip
  .yarn/cache/@tanstack-react-query-devtools-npm-4.33.0-a6a3309037-f8160f9536.zip
  .yarn/cache/@tanstack-react-query-devtools-npm-5.0.0-rc.1-bfc7881f03-0b8270adce.zip
  .yarn/cache/@tanstack-react-query-npm-4.33.0-e64030efd4-b3cf4afa42.zip
  .yarn/cache/@tanstack-react-query-npm-5.0.0-rc.1-3cb8a07631-418018e251.zip
  .yarn/cache/copy-anything-npm-3.0.5-562d15fb3f-d39f6601c1.zip
  .yarn/cache/is-what-npm-4.1.15-328677a458-fe27f6cd4a.zip
  .yarn/cache/remove-accents-npm-0.4.2-7cb341092a-84a6988555.zip
  .yarn/cache/superjson-npm-1.13.1-39607ca2e6-9c8c664a92.zip
  .yarn/cache/use-sync-external-store-npm-1.2.0-44f75d2564-5c639e0f8d.zip
  package.json
  src/components/detail/StudyDetailContent.tsx
  src/components/form/StudyForm.tsx
  src/components/search/StudyList.tsx
  src/hooks/mutations/useCreateStudy.ts
  src/hooks/mutations/useDeleteStudy.ts
  src/hooks/mutations/useDeleteUser.ts
  src/hooks/mutations/useEditStudy.ts
  src/hooks/mutations/usePutUser.ts
  src/hooks/queries/useGetCategories.ts
  src/hooks/queries/useGetProfile.ts
  src/hooks/queries/useGetStudy.ts
  src/pages/_app.tsx
  src/pages/study/create/index.tsx
  src/pages/study/detail/edit/[id].tsx
  yarn.lock
Labels: 🚀 Refactor

#108 [CRES-93] 작성자가 아닌 경우 및 모집이 마감된 경우 페이지 접근 제한
  src/components/form/StudyForm.tsx
  src/pages/study/detail/edit/[id].tsx
Labels: ✨ Feature
