Repository crescenders/crescendo-frontend, pull requests merged in 2023-08, with the labels that each got.

#45 [CRES-51] 정보수정 페이지 UI 구현
  README.md
  public/svg/clear_button.svg
  src/components/common/Header.tsx
  src/components/common/Input.tsx
  src/components/common/NavigateList.tsx
  src/constants/index.ts
  src/constants/validation.ts
  src/hooks/useModal.ts
  src/pages/mypage/edit/index.tsx
  src/utils/validate.ts
Labels: ✨ Feature

#49 [CRES-55] 무한 스크롤 기능 구현
  src/apis/study/study.d.ts
  src/apis/study/studyApi.ts
  src/components/common/Card.tsx
  src/components/common/SelectBox.tsx
  src/hooks/query/useGetStudy.ts
  src/hooks/useIntersection.ts
  src/hooks/useIsMounted.ts
  src/hooks/useIsWorker.ts
  src/hooks/useModal.ts
  src/mocks/browser.ts
  src/mocks/data/studyList.json
  src/mocks/handlers/studyHandlers.ts
  src/mocks/server.ts
  src/pages/index.tsx
  src/pages/search/index.tsx
Labels: ✨ Feature

#54 [CRES-57] Suspense, lazy import 적용
  src/components/common/Header.tsx
  src/components/common/Loader.tsx
  src/pages/_app.tsx
  tailwind.config.ts
Labels: ✨ Feature

#50 [CRES-44] 토스트 메시지 컴포넌트 구현
  public/svg/toast_fail.svg
  public/svg/toast_success.svg
  src/components/common/Layout.tsx
  src/components/common/Toast.tsx
  src/components/modal/BasicModal.tsx
  src/components/modal/DeleteModal.tsx
  src/components/modal/EditModal.tsx
  src/components/modal/LoginModal.tsx
  src/components/modal/SubmitModal.tsx
  src/components/portal/ToastPortal.tsx
  src/hooks/useToast.ts
  src/pages/_document.tsx
  src/recoil/toast.ts
Labels: ✨ Feature

#55 [CRES-54] 태그 컴포넌트 추상화 구현
  public/svg/clear_button_nobackground.svg
  src/components/common/TagInput.tsx
Labels: ✨ Feature

#58 [CRES-60] API 수정사항 반영
  src/apis/auth/auth.d.ts
  src/apis/auth/authApi.ts
  src/apis/instance.ts
  src/apis/user/userApi.ts
  src/components/modal/LoginModal.tsx
  src/utils/token.ts
Labels: 🛠️ Refactor

#60 [CRES-61] 정보수정, 회원탈퇴 기능 구현
  src/apis/instance.ts
  src/components/common/NavigateList.tsx
  src/components/common/Toast.tsx
  src/components/modal/LoginModal.tsx
  src/hooks/mutations/useDeleteUser.ts
  src/hooks/mutations/usePutUser.ts
  src/hooks/queries/useGetStudy.ts
  src/hooks/useDeleteToken.ts
  src/pages/mypage/edit/index.tsx
  src/pages/search/index.tsx
  src/utils/token.ts
Labels: ✨ Feature

#65 [CRES-61] 검색 결과 페이지 Skeleton UI 적용 및 Suspense 개선
  src/components/common/Header.tsx
  src/components/common/Loader.tsx
  src/components/search/StudyList.tsx
  src/components/skeleton/StudyListSkeleton.tsx
  src/mocks/data/studyList.json
  src/mocks/handlers/studyHandlers.ts
  src/pages/_app.tsx
  src/pages/search/index.tsx
  tailwind.config.ts
Labels: ✨ Feature

#62 [CRES-53] 캘린더 컴포넌트 구현
  .yarn/cache/@babel-runtime-npm-7.22.10-2771d0ecab-524d41517e.zip
  .yarn/cache/date-fns-npm-2.30.0-895c790e0f-f7be015232.zip
  .yarn/cache/regenerator-runtime-npm-0.14.0-e060897cf7-1c977ad82a.zip
  package.json
  public/svg/arrow_down.svg
  public/svg/calendar.svg
  src/components/common/Calendar.tsx
  src/components/common/SelectDateBox.tsx
  src/constants/index.ts
  tailwind.config.ts
  yarn.lock
Labels: ✨ Feature

#64 [CRES-62] 내 정보 조회 API 연동
  src/components/common/Header.tsx
  src/components/modal/LoginModal.tsx
  src/hooks/mutations/usePutUser.ts
  src/hooks/queries/useGetProfile.ts
  src/pages/mypage/edit/index.tsx
Labels: ✨ Feature

#68 [CRES-67] 스터디 상세페이지 구현
  public/svg/arrow_up.svg
  src/apis/study/study.d.ts
  src/apis/study/studyApi.ts
  src/components/common/TextArea.tsx
  src/components/detail/ApplyBottomSheet.tsx
  src/components/detail/StudyDetailContent.tsx
  src/components/manage/AssignmentCard.tsx
  src/components/search/StudyList.tsx
  src/hooks/queries/useGetStudy.ts
  src/mocks/data/studyInfo.json
  src/mocks/handlers/studyHandlers.ts
  src/pages/study/detail/[id].tsx
  src/utils/formatUTC.ts
  tailwind.config.ts
Labels: ✨ Feature

#69 [CRES-66] 스터디 개설 페이지 구현
  .yarn/cache/@types-quill-npm-1.3.10-4ddf84ba7e-e629157d11.zip
  .yarn/cache/clone-npm-2.1.2-1d491c6629-aaf106e9bc.zip
  .yarn/cache/deep-equal-npm-1.1.1-67ff9c29b9-f92686f2c5.zip
  .yarn/cache/eventemitter3-npm-2.0.3-71d4ac3a65-dfbf4a0714.zip
  .yarn/cache/extend-npm-3.0.2-e1ca07ac54-a50a8309ca.zip
  .yarn/cache/fast-diff-npm-1.1.2-907d4b29ef-2ef726603e.zip
  .yarn/cache/parchment-npm-1.1.4-a3bac35728-4799756742.zip
  .yarn/cache/quill-delta-npm-3.6.3-3ae240a64d-e62ed33983.zip
  .yarn/cache/quill-npm-1.3.7-c79f7446fc-db3e265a84.zip
  .yarn/cache/react-quill-npm-2.0.0-f2d141fe1d-568e28656a.zip
  package.json
  public/svg/upload_image.svg
  src/@types/index.d.ts
  src/apis/study/study.d.ts
  src/apis/study/studyApi.ts
  src/components/common/Calendar.tsx
  src/components/common/Header.tsx
  src/components/common/Loader.tsx
  src/components/common/SelectDateBox.tsx
  src/components/common/Slider.tsx
  src/components/common/TagInput.tsx
  src/components/common/UploadImage.tsx
  src/components/editor/QuillEditor.tsx
  src/components/editor/TextEditor.tsx
  src/constants/categories.ts
  src/constants/index.ts
  src/constants/validation.ts
  src/hooks/mutations/useCreateStudy.ts
  src/hooks/useStudyForm.ts
  src/mocks/handlers/studyHandlers.ts
  src/pages/index.tsx
  src/pages/study/create/index.tsx
  src/utils/validate.ts
  yarn.lock
Labels: ✨ Feature

#71 [CRES-70] react-query v3 -> v4 마이그레이션
  .yarn/cache/@tanstack-match-sorter-utils-npm-8.8.4-488b98c113-d005f50075.zip
  .yarn/cache/@tanstack-query-core-npm-4.33.0-10e4a91d19-fae325f1d7.zip
  .yarn/cache/@tanstack-react-query-devtools-npm-4.33.0-a6a3309037-f8160f9536.zip
  .yarn/cache/@tanstack-react-query-npm-4.33.0-e64030efd4-b3cf4afa42.zip
  .yarn/cache/broadcast-channel-npm-3.7.0-81ceba70bb-803794c48d.zip
  .yarn/cache/copy-anything-npm-3.0.5-562d15fb3f-d39f6601c1.zip
  .yarn/cache/detect-node-npm-2.1.0-e8de0e94f7-832184ec45.zip
  .yarn/cache/is-what-npm-4.1.15-328677a458-fe27f6cd4a.zip
  .yarn/cache/js-sha3-npm-0.8.0-decf3ddcfa-75df77c1fc.zip
  .yarn/cache/match-sorter-npm-6.3.1-ff3565ebb9-a4b02b676a.zip
  .yarn/cache/microseconds-npm-0.2.0-dbdb8ab8bb-22bfa8553f.zip
  .yarn/cache/nano-time-npm-1.0.0-6eca938be8-eef8548546.zip
  .yarn/cache/oblivious-set-npm-1.0.0-8e7336b241-f31740ea9c.zip
  .yarn/cache/react-query-npm-3.39.3-72b2a93edf-d2de6a0992.zip
  .yarn/cache/superjson-npm-1.13.1-39607ca2e6-9c8c664a92.zip
  .yarn/cache/unload-npm-2.2.0-c40df6b4d0-88ba950c5f.zip
  .yarn/cache/use-sync-external-store-npm-1.2.0-44f75d2564-5c639e0f8d.zip
  package.json
  src/hooks/mutations/useCreateStudy.ts
  src/hooks/mutations/useDeleteUser.ts
  src/hooks/mutations/usePutUser.ts
  src/hooks/queries/useGetProfile.ts
  src/hooks/queries/useGetStudy.ts
  src/pages/_app.tsx
  yarn.lock
Labels: chore
