Repository crescenders/crescendo-frontend, pull requests merged in 2023-11, with the labels that each got.

#154 [CRES-114] 스터디 진행도가 100% 이상인 경우 그 이상 초과되는 것을 수정한다.
  src/components/common/ProgressBar.tsx
  src/pages/study/assignment/[id].tsx
  src/utils/getProgress.ts
Labels: 🚨 버그

#157 [CRES-109] 제출된 과제 목록 페이지 구현
  src/apis/submission/submission.d.ts
  src/apis/submission/submissionApi.ts
  src/components/manage/AssignmentCard.tsx
  src/components/skeleton/SubmissionListSkeleton.tsx
  src/components/submission/SubmissionList.tsx
  src/hooks/queries/useGetSubmission.ts
  src/pages/study/assignment/submission/[...id].tsx
Labels: 기능구현 ✅

#156 [CRES-115] Error Boundary를 통해 에러를 핸들링한다.
  public/svg/retry.svg
  src/components/errorboundary/ErrorBoundary.tsx
  src/components/errorboundary/ErrorFallback.tsx
  src/components/errorboundary/GlobalErrorBoundary.tsx
  src/components/manage/AssignmentCard.tsx
  src/mocks/browser.ts
  src/mocks/handlers/assignmentHandlers.ts
  src/mocks/server.ts
  src/pages/404.tsx
  src/pages/_app.tsx
  src/pages/search/index.tsx
  src/pages/study/assignment/[id].tsx
  src/pages/study/assignment/detail/[...id].tsx
  src/utils/getErrorMessage.ts
Labels: 기능구현 ✅, 🚨 버그

#159 [CRES-110] 멤버 모달 개선
  src/apis/application/applicationApi.ts
  src/components/detail/ApplyBottomSheet.tsx
  src/components/member/ApplicationList.tsx
  src/components/member/MemberCard.tsx
  src/components/member/MemberList.tsx
  src/components/modal/DeleteMemberModal.tsx
  src/hooks/mutations/useApplyStudy.ts
  src/hooks/mutations/useDeleteApplication.ts
  src/hooks/mutations/useDeleteMember.ts
  src/hooks/mutations/usePostApplication.ts
  src/hooks/mutations/useReplyApplication.ts
  src/pages/study/member/[id].tsx
Labels: 리펙토링 🚀

#161 [CRES-119] 사용자 유치 전 버그해결 및 수정사항을 반영한다.
  src/components/common/Card.tsx
  src/components/common/DropBox.tsx
  src/components/detail/AssignmentDetailContent.tsx
  src/components/detail/StudyDetailContent.tsx
  src/components/mypage/PendingApprovalList.tsx
  src/components/mypage/StudyInProgressList.tsx
  src/middleware.ts
  src/pages/mypage/manage.tsx
  src/pages/study/assignment/[id].tsx
  src/pages/study/assignment/detail/[...id].tsx
  src/pages/study/assignment/submission/[...id].tsx
  src/styles/global.css
Labels: 리펙토링 🚀

#165 [CRES-117] 제출된 과제 상세 페이지 구현
  src/apis/submission/submissionApi.ts
  src/components/detail/SubmissionDetailContent.tsx
  src/components/submission/SubmissionList.tsx
  src/hooks/mutations/useDeleteSubmission.ts
  src/hooks/mutations/useEditSubmission.ts
  src/hooks/queries/useGetSubmission.ts
  src/pages/study/assignment/submission/detail/[...id].tsx
  src/pages/study/assignment/submission/edit/[...id].tsx
Labels: 기능구현 ✅

#169 [CRES-118] 스터디 개설 페이지 개선
  src/components/common/SelectDateBox.tsx
  src/components/common/TagInput.tsx
Labels: 리펙토링 🚀

#173 [CRES-123] 토큰 재발급 이슈 해결
  src/apis/application/applicationApi.ts
  src/apis/assignment/assignmentApi.ts
  src/apis/auth/authApi.ts
  src/apis/category/categoryApi.ts
  src/apis/instance.ts
  src/apis/member/memberApi.ts
  src/apis/study/studyApi.ts
  src/apis/submission/submissionApi.ts
  src/apis/tag/tagApi.ts
  src/apis/user/userApi.ts
Labels: 🚨 버그

#177 [CRES-124] userAgent가 모바일 환경일 경우 데스크탑 접속 권장 페이지 렌더링
  public/svg/mobile.svg
  src/components/common/MobilePage.tsx
  src/components/common/Toast.tsx
  src/pages/_app.tsx
  src/utils/getDevice.ts
Labels: 기능구현 ✅

#179 [CRES-125] 과제 보기 페이지 리펙토링
  src/apis/assignment/assignmentApi.ts
  src/components/assignment/AssignmentList.tsx
  src/components/common/MenuBar.tsx
  src/components/skeleton/AssignmentListSkeleton.tsx
  src/components/skeleton/StudyListSkeleton.tsx
  src/hooks/queries/useGetAssignment.ts
  src/pages/study/assignment/[id].tsx
  src/pages/study/assignment/detail/[...id].tsx
Labels: 리펙토링 🚀

#183 [CRES-127] 과제 작성일 표기 오류 수정
  src/components/detail/AssignmentDetailContent.tsx
Labels: 🚨 버그

#187 [CRES-129] 유틸함수 테스트 코드 작성
  __tests__/utils/cookie.test.ts
  __tests__/utils/formatUTC.test.ts
  __tests__/utils/getDevice.test.ts
  __tests__/utils/getErrorMessage.test.ts
  __tests__/utils/getProgress.test.ts
  __tests__/utils/validate.test.ts
Labels: 테스트 🧪

#189 [CRES-130] Custom hook 테스트 코드 작성
  __tests__/hooks/useIsMounted.test.ts
  __tests__/hooks/useModal.test.ts
  __tests__/hooks/useScript.test.tsx
  src/hooks/useScript.ts
Labels: 테스트 🧪

#175 [CRES-122] 사이트 제목 및 파비콘 등록
  public/favicon.ico
  public/open_graph.png
  public/robots.txt
  src/components/common/CustomHead.tsx
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/sitemap.xml.tsx
Labels: 기능구현 ✅, 설정 ⚙️

#196 [CRES-134] 공통 컴포넌트 유닛 & 통합테스트 코드 작성
  __tests__/components/common/Button.test.tsx
  __tests__/components/common/DropBox.test.tsx
  __tests__/components/common/Header.test.tsx
  __tests__/components/common/Input.test.tsx
  __tests__/components/common/TextArea.test.tsx
  jest.config.mjs
  setupTests.ts
  src/components/common/Input.tsx
  src/components/common/TextArea.tsx
  tsconfig.json
Labels: 테스트 🧪

#192 [CRES-133] 메타 태그 적용 안 되는 문제 해결
  src/components/common/CustomHead.tsx
  src/pages/_document.tsx
Labels: 🛠️ fix

#199 [CRES-136] 진행도와 퍼센트 문구의 간격을 조정한다.
  __tests__/components/common/DropBox.test.tsx
  src/components/assignment/AssignmentList.tsx
Labels: 디자인 🎨

#195 [CRES-131] 참여 신청 가능 권한 검증 및 신청 거절 모달 수정
  src/components/detail/ApplyBottomSheet.tsx
  src/components/member/ApplicationList.tsx
  src/components/member/MemberList.tsx
  src/components/modal/DeleteMemberModal.tsx
  src/components/modal/MemberModal.tsx
  src/hooks/queries/useGetStudyMembers.ts
Labels: 리펙토링 🚀

#206 [CRES-137] 사이트맵 날짜 형식 변경
  src/pages/sitemap.xml.tsx
Labels: 🛠️ fix

#208 [CRES-200] Package.json 수정
  package.json
  yarn.lock
Labels: 문서 📄

#204 [CRES-132] 과제 제출 가능 기간 검증 및 디자인 개선
  src/@types/index.d.ts
  src/components/detail/SubmissionDetailContent.tsx
  src/hooks/mutations/usePostApplication.ts
  src/hooks/mutations/usePostSubmission.ts
Labels: 리펙토링 🚀

#210 [CRES-139] 사용자 시나리오에 따른 E2E 테스트 작성
  .github/workflows/frontend-ci.yml
  cypress.config.js
  cypress/e2e/login.cy.ts
  cypress/e2e/mobile.cy.ts
  cypress/e2e/search.cy.ts
  package.json
Labels: 테스트 🧪

#212 인원 항목 크기가 줄어드는 현상 해결
  src/components/manage/OpenStudyCard.tsx
Labels: 🚨 버그

#213 zero runtime을 위한 tw 제거 작업
  .prettierrc.js
  .yarn/cache/prettier-plugin-tailwind-styled-components-npm-0.0.2-3761add64d-9ef540c8ca.zip
  .yarn/cache/tailwind-merge-npm-1.12.0-e272b9353d-5ef323eec1.zip
  .yarn/cache/tailwind-styled-components-npm-2.2.0-abf8227684-482eb7651a.zip
  package.json
  src/components/common/AuthLayout.tsx
  src/components/common/Button.tsx
  src/components/common/Calendar.tsx
  src/components/common/Card.tsx
  src/components/common/HomeLayout.tsx
  src/components/common/Input.tsx
  src/components/common/Layout.tsx
  src/components/common/MenuBar.tsx
  src/components/common/PageLayout.tsx
  src/components/common/SelectBox.tsx
  src/components/common/SelectDateBox.tsx
  src/components/common/Slider.tsx
  src/components/common/TagInput.tsx
  src/components/common/TextArea.tsx
  src/components/detail/ApplyBottomSheet.tsx
  src/components/detail/StudyDetailContent.tsx
  src/components/home/RandomStudyList.tsx
  src/components/manage/OpenStudyCard.tsx
  src/components/member/MemberCard.tsx
  src/components/modal/BasicModal.tsx
  src/components/modal/EditModal.tsx
  src/components/modal/LoginModal.tsx
  src/components/modal/SubmitModal.tsx
  src/components/portal/ModalPortal.tsx
  src/components/search/StudyList.tsx
  src/pages/index.tsx
  src/pages/login/index.tsx
  src/pages/mypage/edit.tsx
  src/pages/mypage/manage.tsx
  src/pages/search/index.tsx
  src/pages/study/assignment/submission/[...id].tsx
  src/pages/study/detail/[id].tsx
  src/pages/study/member/[id].tsx
  yarn.lock
Labels: 리펙토링 🚀, 👨‍👧‍👦 페어프로그래밍

#215 모바일 페이지 제거
  __tests__/utils/getDevice.test.ts
  cypress/e2e/mobile.cy.ts
  src/pages/_app.tsx
  src/utils/getDevice.ts
Labels: 리펙토링 🚀

#217 구글 검색 결과에 표시할 파비콘 적용
  public/next.svg
  public/vercel.svg
  src/pages/_document.tsx
Labels: 기능구현 ✅

#219 배포 이관작업
  .github/workflows/frontend-cd.yml
  build.sh
Labels: 인프라

#221 빌드 시 컴파일러가 QuillEditor가 JSX로 반환하지 않아 생기는 문제 수정
  src/components/editor/QuillEditor.tsx
Labels: 🚨 버그

#225 상세페이지에 진입시 스켈레톤 UI가 보이지 않는 현상 해결
  src/components/common/Card.tsx
  src/components/detail/StudyDetailContent.tsx
  src/pages/study/detail/[id].tsx
Labels: 🚨 버그

#226 Layout Shift 방지를 위한 height 지정
  src/components/home/Banner.tsx
Labels: 리펙토링 🚀

#227 TanStack Query의 suspense 옵션을 사용함으로써 useQuery가 서버에서도 실행이 되는 문제 해결
  src/components/assignment/AssignmentList.tsx
  src/components/common/Card.tsx
  src/components/common/Header.tsx
  src/components/common/SSRSafeSuspense.tsx
  src/components/detail/ApplyBottomSheet.tsx
  src/components/detail/AssignmentDetailContent.tsx
  src/components/detail/StudyDetailContent.tsx
  src/components/detail/SubmissionDetailContent.tsx
  src/components/home/Banner.tsx
  src/components/mypage/ApprovedStudyList.tsx
  src/components/mypage/DisApprovedStudyList.tsx
  src/components/mypage/StudyInProgressList.tsx
  src/components/skeleton/ApplyStudySkeleton.tsx
  src/components/skeleton/StatusStudySkeleton.tsx
  src/hooks/queries/useGetAssignment.ts
  src/hooks/queries/useGetStudy.ts
  src/hooks/queries/useGetSubmission.ts
  src/pages/_app.tsx
  src/pages/mypage/apply.tsx
  src/pages/mypage/status.tsx
  src/pages/search/index.tsx
  src/pages/study/assignment/[id].tsx
  src/pages/study/assignment/detail/[...id].tsx
  src/pages/study/assignment/edit/[...id].tsx
  src/pages/study/assignment/submission/[...id].tsx
  src/pages/study/assignment/submission/detail/[...id].tsx
  src/pages/study/assignment/submission/edit/[...id].tsx
  src/pages/study/assignment/submission/submit/[...id].tsx
  src/pages/study/detail/[id].tsx
  src/pages/study/detail/edit/[id].tsx
  src/pages/study/member/[id].tsx
Labels: 🚨 버그

#229 검색 엔진 최적화 및 초기 렌더링 속도 향상을 위한 SSR 적용
  public/robots.txt
  src/components/common/TextArea.tsx
  src/components/detail/ApplyBottomSheet.tsx
  src/components/detail/StudyDetailContent.tsx
  src/components/detail/SubmissionDetailContent.tsx
  src/components/home/Banner.tsx
  src/components/submission/SubmissionList.tsx
  src/hooks/queries/useGetAssignment.ts
  src/hooks/queries/useGetStudy.ts
  src/hooks/queries/useGetSubmission.ts
  src/hooks/queries/useGetTags.ts
  src/pages/index.tsx
  src/pages/study/assignment/detail/[...id].tsx
  src/pages/study/assignment/submission/detail/[...id].tsx
  src/pages/study/detail/[id].tsx
Labels: 리펙토링 🚀

#232 Suspense와 Error Boundary를 일괄적으로 처리하는 AsyncBoundary 구현
  src/components/async/AsyncBoundary.tsx
  src/components/async/SSRSafeSuspense.tsx
  src/components/modal/MemberModal.tsx
  src/pages/mypage/apply.tsx
  src/pages/mypage/status.tsx
  src/pages/search/index.tsx
  src/pages/study/assignment/[id].tsx
  src/pages/study/assignment/detail/[...id].tsx
  src/pages/study/assignment/submission/[...id].tsx
  src/pages/study/assignment/submission/detail/[...id].tsx
Labels: 기능구현 ✅, 리펙토링 🚀

#234 메인페이지 디자인 수정
  src/components/common/Footer.tsx
  src/components/common/HomeLayout.tsx
  src/components/home/RandomStudyList.tsx
Labels: 리펙토링 🚀

#236 모바일에서 좌우로 스크롤 되는 현상 수정
  src/components/common/HomeLayout.tsx
  src/components/common/Layout.tsx
Labels: 🚨 버그

#238 모바일 환경에 대응할 수 있도록 디자인을 개선한다.
  __tests__/utils/getDevice.test.ts
  src/components/common/Header.tsx
  src/components/common/NavigateList.tsx
  src/components/common/SelectBox.tsx
  src/components/detail/ApplyBottomSheet.tsx
  src/components/detail/StudyDetailContent.tsx
  src/components/home/Banner.tsx
  src/constants/index.ts
  src/pages/search/index.tsx
  src/utils/getDevice.ts
  tsconfig.json
Labels: 리펙토링 🚀

#240 모바일에서 좌우로 스크롤 되는 현상 수정
  src/components/common/PageLayout.tsx
Labels: 🚨 버그

#244 UI 개선사항 적용
  src/components/common/AuthLayout.tsx
  src/components/common/Header.tsx
  src/components/common/NavigateList.tsx
  src/components/common/SelectBox.tsx
  src/components/home/Banner.tsx
  src/hooks/useClickAway.ts
  src/pages/login/index.tsx
Labels: 리펙토링 🚀

#248 과제 상세페이지가 로딩 되기 전 정적 생성된 페이지가 보이는 현상 수정
  src/components/detail/AssignmentDetailContent.tsx
Labels: 🚨 버그

#252 스터디 개설 페이지의 이미지 제거 버튼 텍스트가 안 보이는 문제를 해결한다.
  src/components/common/UploadImage.tsx
Labels: 🚨 버그

#254 리드미 업데이트
  README.md
Labels: 문서 📄

#255 스터디 수정 페이지 오류 해결
  src/components/manage/MyStudyList.tsx
  src/pages/mypage/manage.tsx
  src/pages/study/detail/edit/[id].tsx
Labels: 🛠️ fix

#257 서버에서 정적생성된 페이지와 불일치하는 현상 해결
  src/components/common/Header.tsx
Labels: 🚨 버그
