Repository crescenders/crescendo-frontend, pull requests merged in 2023-06, with the labels that each got.

#19 [CRES-31] feat: MenuBar 컴포넌트 작성
  src/components/common/MenuBar.tsx
Labels: ✨ Feature

#18 [CRES-35] feat: 개설한 스터디 페이지 퍼블리싱
  public/svg/person.svg
  public/svg/trashcan.svg
  src/components/common/Header.tsx
  src/components/manage/OpenStudyCard.tsx
  src/pages/mypage/index.tsx
  src/pages/mypage/studymanage.tsx
  tailwind.config.ts
Labels: ✨ Feature

#22 [CRES-32] feat: 카드 컴포넌트 작성
  next.config.js
  public/svg/check_circle.svg
  src/components/common/Card.tsx
  src/pages/test/card.tsx
  src/pages/test/modal/basic.tsx
  src/pages/test/modal/delete.tsx
  src/pages/test/modal/login.tsx
  src/utils/getDiffDate.ts
Labels: ✨ Feature, 🐰 리뷰 요청

#21 [CRES-37] feat: 등록한 과제 페이지 퍼블리싱
  public/svg/plus.svg
  src/components/common/Header.tsx
  src/components/manage/AssignmentCard.tsx
  src/components/manage/OpenStudyCard.tsx
  src/pages/studymanage/assignment/[id].tsx
  src/pages/studymanage/index.tsx
  tailwind.config.ts
Labels: ✨ Feature

#25 [CRES-38] feat: 과제 보기 페이지 퍼블리싱
  .eslintrc.json
  public/svg/edit.svg
  public/svg/edit_clicked.svg
  public/svg/link.svg
  public/svg/success.svg
  public/svg/trashcan_clicked.svg
  src/components/common/Header.tsx
  src/components/common/ProgressBar.tsx
  src/components/manage/AssignmentCard.tsx
  src/components/manage/OpenStudyCard.tsx
  src/components/modal/BasicModal.tsx
  src/pages/study/detail/[id].tsx
  src/pages/study/detail/assignment/[id].tsx
  src/pages/study/manage/assignment/[id].tsx
  src/pages/study/manage/index.tsx
Labels: ✨ Feature

#31 [CRES-40] feat: 신청한 스터디 페이지 퍼블리싱
  src/pages/study/apply/index.tsx
Labels: ✨ Feature

#33 [CRES-42] feat: 셀렉트 박스 컴포넌트 구현
  public/svg/chevron-down.svg
  src/components/common/Header.tsx
  src/components/common/SelectBox.tsx
  src/components/modal/ModalLayout.tsx
  src/constants/categories.ts
  src/pages/index.tsx
  src/pages/search/index.tsx
  tsconfig.json
Labels: ✨ Feature

#35 [CRES-43] feat: 구글 소셜 로그인 구현 & Axios instance 생성
  config.ts
  src/@types/index.d.ts
  src/apis/auth/auth.d.ts
  src/apis/auth/authApi.ts
  src/apis/instance.ts
  src/apis/user/user.d.ts
  src/apis/user/userApi.ts
  src/components/common/Header.tsx
  src/components/common/NavigateList.tsx
  src/components/modal/LoginModal.tsx
  src/hooks/useScript.ts
  src/pages/_app.tsx
  src/recoil/auth.ts
  src/utils/localStorage.ts
  src/utils/token.ts
  tsconfig.json
Labels: ✨ Feature

#37 [ CRES-46] refactor: 마운트 여부 useIsMouted 훅으로 분리 & 로그인 여부 예외처리
  .yarn/cache/prettier-plugin-tailwindcss-npm-0.2.8-f24120e3dc-0c99295f1f.zip
  .yarn/cache/prettier-plugin-tailwindcss-npm-0.3.0-a8491b7f62-007c095584.zip
  package.json
  src/apis/auth/authApi.ts
  src/components/common/Header.tsx
  src/components/modal/LoginModal.tsx
  src/hooks/useIsMounted.ts
  src/pages/home/index.tsx
  yarn.lock
Labels: 🛠️ Refactor
