Repository crescenders/crescendo-frontend, pull requests merged in 2023-10, with the labels that each got.

#113 [CRES-89] 메인페이지 랜덤 스터디 목록 구현
  src/components/home/HomeStudyList.tsx
  src/components/search/StudyList.tsx
  src/components/skeleton/StudyListSkeleton.tsx
  src/hooks/mutations/usePutUser.ts
  src/hooks/queries/useGetStudy.ts
  src/pages/index.tsx
  src/pages/login/index.tsx
  src/pages/search/index.tsx
Labels: ✨ Feature

#114 [CRES-91] 내가 맡은 스터디 페이지 구현
  src/apis/study/studyApi.ts
  src/components/manage/MyStudyList.tsx
  src/components/manage/OpenStudyCard.tsx
  src/components/skeleton/MyStudyListSkeleton.tsx
  src/constants/index.ts
  src/hooks/mutations/useDeleteStudy.ts
  src/hooks/queries/useGetStudy.ts
  src/middleware.ts
  src/pages/study/manage/index.tsx
Labels: ✨ Feature

#116 [CRES-96] 로그아웃 API 연동 및 기타 버그 개선
  apsspec.yml
  build.sh
  config.ts
  src/apis/auth/authApi.ts
  src/apis/instance.ts
  src/components/common/Layout.tsx
  src/components/common/NavigateList.tsx
  src/components/common/PageLayout.tsx
  src/components/home/HomeStudyList.tsx
  src/components/home/RandomStudyList.tsx
  src/components/modal/LoginModal.tsx
  src/constants/index.ts
  src/hooks/mutations/usePostLogout.ts
  src/mocks/browser.ts
  src/mocks/handlers/handlers.ts
  src/mocks/server.ts
  src/pages/index.tsx
  src/pages/login/index.tsx
Labels: ✨ Feature, 🚨 버그

#121 [CRES-97] 검색 결과 페이지에서 뒤로가기를 했을 때 스켈레톤 UI가 뜨는 현상을 해결한다.
  src/components/search/NotFoundStudyList.tsx
  src/components/search/StudyList.tsx
Labels: 🛠️ fix

#118 [CRES-94] 스터디 참여 신청 api 연동
  src/apis/study/studyApi.ts
  src/components/common/Toast.tsx
  src/components/detail/ApplyBottomSheet.tsx
  src/hooks/mutations/useApplyStudy.ts
  src/pages/_app.tsx
Labels: ✨ Feature

#122 [CRES-98] 리프레쉬 토큰 재발급 과정에서 에러 상황에 대처할 수 있도록 인터셉터 예외처리 로직 수정
  src/apis/auth/authApi.ts
  src/apis/instance.ts
  src/components/common/AuthLayout.tsx
  src/components/common/NavigateList.tsx
  src/components/common/PageLayout.tsx
  src/pages/login/index.tsx
Labels: 🚨 버그

#124 [CRES-99] 스터디 상세페이지 리더 이메일 정보 추가
  src/apis/study/study.d.ts
  src/components/detail/StudyDetailContent.tsx
Labels: 🚀 Refactor

#126 [CRES-95] 스터디 참여 신청자 모달 구현
  public/svg/apply_list.svg
  public/svg/check.svg
  public/svg/cross.svg
  public/svg/member_list.svg
  src/apis/study/study.d.ts
  src/apis/study/studyApi.ts
  src/components/manage/MemberCard.tsx
  src/components/manage/MemberList.tsx
  src/components/manage/MyStudyList.tsx
  src/components/manage/OpenStudyCard.tsx
  src/components/modal/MemberModal.tsx
  src/hooks/queries/useGetStudyMembers.ts
  src/mocks/data/memberList.json
  src/mocks/handlers/studyHandlers.ts
  src/pages/study/detail/assignment/[id].tsx
  src/pages/study/manage/assignment/[id].tsx
  src/styles/globals.css
Labels: ✨ Feature

#128 [CRES-101] 멤버 보기 페이지 구현
  public/svg/emoji_inbox.svg
  public/svg/emoji_members.svg
  src/apis/application/application.d.ts
  src/apis/application/applicationApi.ts
  src/apis/member/member.d.ts
  src/apis/member/memberApi.ts
  src/apis/study/study.d.ts
  src/apis/study/studyApi.ts
  src/components/common/MenuBar.tsx
  src/components/manage/MemberList.tsx
  src/components/manage/OpenStudyCard.tsx
  src/components/member/ApplicationList.tsx
  src/components/member/MemberCard.tsx
  src/components/member/MemberList.tsx
  src/components/modal/MemberModal.tsx
  src/hooks/mutations/useApplyStudy.ts
  src/hooks/mutations/useDeleteMember.ts
  src/hooks/mutations/useReplyApplication.ts
  src/hooks/queries/useGetApplications.ts
  src/hooks/queries/useGetStudyMembers.ts
  src/mocks/browser.ts
  src/mocks/data/memberList.json
  src/mocks/handlers/memberHandlers.ts
  src/mocks/handlers/studyHandlers.ts
  src/mocks/server.ts
  src/pages/mypage/apply/index.tsx
  src/pages/mypage/current-status/index.tsx
  src/pages/study/detail/[id].tsx
  src/pages/study/detail/assignment/[id].tsx
  src/pages/study/detail/member/[id].tsx
  src/pages/study/manage/assignment/[id].tsx
Labels: ✨ Feature

#130 [CRES-100] 마이페이지 구현
  src/apis/study/study.d.ts
  src/apis/study/studyApi.ts
  src/apis/user/user.d.ts
  src/apis/user/userApi.ts
  src/components/common/Card.tsx
  src/components/common/Layout.tsx
  src/components/common/MenuBar.tsx
  src/components/common/PageLayout.tsx
  src/components/modal/MemberModal.tsx
  src/components/mypage/ApprovedStudyList.tsx
  src/components/mypage/DisApprovedStudyList.tsx
  src/components/mypage/PendingApprovalList.tsx
  src/components/mypage/StudyInProgressList.tsx
  src/constants/index.ts
  src/hooks/queries/useGetStudy.ts
  src/pages/mypage/apply/index.tsx
  src/pages/mypage/current-status/index.tsx
  src/pages/mypage/index.tsx
  src/pages/mypage/manage/index.tsx
  src/pages/mypage/status/index.tsx
  src/styles/globals.css
Labels: ✨ Feature

#136 [CRES-106] 404 페이지 구현
  src/pages/404.tsx
  tailwind.config.ts
Labels: ✨ Feature

#134 [CRES-107] 내가 맡은 스터디, 멤버 보기 페이지 반응형 디자인
  src/pages/mypage/manage/index.tsx
  src/pages/study/detail/member/[id].tsx
Labels: 🎨 design

#138 [CRES-103] 과제 등록/수정 및 목록 페이지 구현
  public/svg/edit2.svg
  public/svg/more.svg
  public/svg/run.svg
  public/svg/trash.svg
  src/@types/index.d.ts
  src/apis/assignment/assignment.d.ts
  src/apis/assignment/assignmentApi.ts
  src/apis/user/user.d.ts
  src/components/common/DropBox.tsx
  src/components/common/Loader.tsx
  src/components/common/ProgressBar.tsx
  src/components/common/TextArea.tsx
  src/components/detail/AssignmentDetailContent.tsx
  src/components/detail/StudyDetailContent.tsx
  src/components/manage/AssignmentCard.tsx
  src/constants/index.ts
  src/hooks/mutations/useDeleteAssignment.ts
  src/hooks/mutations/useDeleteMember.ts
  src/hooks/mutations/useDeleteStudy.ts
  src/hooks/mutations/useEditAssignment.ts
  src/hooks/mutations/useEditStudy.ts
  src/hooks/mutations/usePostAssignment.ts
  src/hooks/queries/useGetAssignment.ts
  src/pages/mypage/apply.tsx
  src/pages/mypage/edit.tsx
  src/pages/mypage/manage.tsx
  src/pages/mypage/status.tsx
  src/pages/study/assignment/[id].tsx
  src/pages/study/assignment/detail/[...id].tsx
  src/pages/study/assignment/edit/[...id].tsx
  src/pages/study/assignment/register/[id].tsx
  src/pages/study/detail/[id].tsx
  src/pages/study/detail/assignment/[id].tsx
  src/pages/study/member/[id].tsx
  src/utils/formatUTC.ts
  src/utils/getProgress.ts
  tailwind.config.ts
Labels: ✨ Feature

#140 [CRES-105] 헤더 및 배너 전체 가로길이 차지하도록 레이아웃 조정
  src/components/common/Header.tsx
  src/components/common/HomeLayout.tsx
  src/components/common/PageLayout.tsx
  src/components/home/Banner.tsx
  src/components/home/RandomStudyList.tsx
  src/pages/index.tsx
Labels: 🐰 리뷰 요청, 🎨 design

#146 [CRES-108] CDN으로 폰트를 가져오는 방식에서 패키지 매니저로 설치하여 폰트 최적화, 기타 피드백 반영
  .yarn/cache/@babel-runtime-npm-7.21.5-7d058028a3-358f2779d3.zip
  .yarn/cache/is-typed-array-npm-1.1.10-fe4ef83cdc-aac6ecb59d.zip
  .yarn/cache/regenerator-runtime-npm-0.13.11-90bf536060-27481628d2.zip
  .yarn/cache/tslib-npm-2.5.0-bb364efebd-ae3ed5f9ce.zip
  .yarn/cache/which-typed-array-npm-1.1.9-9559c95dfc-fe0178ca44.zip
  package.json
  postcss.config.js
  src/components/common/DropBox.tsx
  src/components/common/Header.tsx
  src/components/detail/StudyDetailContent.tsx
  src/components/home/Banner.tsx
  src/constants/validation.ts
  src/pages/_app.tsx
  src/pages/create.tsx
  src/pages/study/create/index.tsx
  src/styles/global.css
  src/styles/globals.css
  tailwind.config.ts
  yarn.lock
Labels: ✨ Feature

#150 [CRES-113] 과제 상세페이지, 검색 페이지 반응형 디자인
  src/components/detail/ApplyBottomSheet.tsx
  src/components/detail/StudyDetailContent.tsx
  src/components/search/StudyList.tsx
  src/pages/search/index.tsx
Labels: 디자인 🎨

#147 [CRES-111] 배너에 보여주는 랜덤 태그 구현
  src/apis/tag/tag.d.ts
  src/apis/tag/tagApi.ts
  src/components/home/Banner.tsx
  src/hooks/queries/useGetTags.ts
Labels: 기능구현 ✅

#148 [CRES-112] 토큰 재발급 과정에서 블랙리스트 응답오는 현상 해결
  src/apis/instance.ts
Labels: 🚨 버그
